    insert into users VALUES ('BRIANCITOsdf','CONTRASEÑA1','MIEMBRO');
    insert into users VALUES ('PABLITO','CONTRASEÑA2','MIEMBRO');
    insert into users VALUES ('CARLITOS','CONTRASEÑA3','MIEMBRO');
    insert into users VALUES ('FRANQUITO','CONTRASEÑA4','MIEMBRO');
    insert into users VALUES ('RAFITA','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('ARMANDITO','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('PEPITO','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('SAMUELITO','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('SERYITO','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('DANIELITO','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('ALEJANDRITO','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('LUKITA','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('ALBERTITO','CONTRASEÑA5','MIEMBRO');
    insert into users VALUES ('JOSECITO','CONTRASEÑA5','ADMIN');
    insert into users VALUES ('a','a','ADMIN');
    insert into users VALUES ('b','b','ADMIN');
    insert into users VALUES ('c','c','ADMIN');
    insert into users VALUES ('d','d','MIEMBRO');
    insert into users VALUES ('e','e','MIEMBRO');
    insert into users VALUES ('f','f','MIEMBRO');
    insert into users VALUES ('g','g','REGISTRADO');


    insert into registrado VALUES (NULL,'a', 'Pablo', 'Garcia','a', '1982/1/05', 'a@YAHOO.ES', 'a', 'Ingenieria', NULL);-- solo representa un club --
    insert into registrado VALUES (NULL,'Javier02', 'Javier', 'Álvarez ','b', '1982/1/05', 'javier@YAHOO.ES', 'a', 'Medicina', NULL);-- solo representa un proyecto --
    insert into registrado VALUES (NULL,'Ivánete', 'Iván', 'Díaz ','c', '1982/1/05', 'Iván@YAHOO.ES', 'a', 'Medio ambiente', NULL);-- representa un club y proyecto --
    insert into registrado VALUES (NULL,'Lucasito', 'Lucas', 'Muñoz ','d', '1982/1/05', 'Lucas@YAHOO.ES', 'a', 'Deporte', NULL);-- solo pertenece un club --
    insert into registrado VALUES (NULL,'Hasan_98', 'Hasan', 'Jiménez ','e', '1982/1/05', 'Hasan@YAHOO.ES', 'a', 'ADE', NULL);-- solo pertenece un proyecto --
    insert into registrado VALUES (NULL,'Moad23', 'Moad', 'Fernández ','f', '1982/1/05', 'Moad@YAHOO.ES', 'a', 'Economia', NULL);-- pertenece un club y proyecto --
    insert into registrado VALUES (NULL,'Lukesito', 'Luke', 'Ruiz ','g', '1982/1/05', 'Luke@YAHOO.ES', 'a', 'BASKET', NULL);-- no pertenece a nada --
    insert into registrado VALUES (NULL,'Pablito', 'PABLO', 'GARCIA','CANTALAPIEDRA', '1996/10/25', 'PABLO@YAHOO.ES','a', 'BOSS', NULL);
    insert into registrado VALUES (NULL,'Alejandritoo', 'ALEJANDRO', 'ORTEGA','ZAFIRO', '1999/10/20', 'ALEX@YAHOO.ES','a', 'PROGRAMADOR', NULL);
    insert into registrado VALUES (NULL,'Carlitos', 'CARLOS', 'GODINO','PEREZ', '1995/5/1', 'CARLOS@YAHOO.ES','a', 'DISEÑADOR WEB', NULL);
    insert into registrado VALUES (NULL,'Albertito', 'ALBERTO', 'RIJA','MON', '1998/1/1', 'ALBERTO@YAHOO.ES','a', NULL, NULL);
    insert into registrado VALUES (NULL,'Danielito', 'DANIEL', 'EGIDO','REMIFA', '2002/10/25', 'DANI@YAHOO.ES','a', 'DORMILON', NULL);
    insert into registrado VALUES (NULL,'Franquitoo', 'FRANCO', 'COLLINS','DORMISTE', '1996/10/1','FRANCO@YAHOO.ES','a', 'JAVASCRIPT', NULL);
    insert into registrado VALUES (NULL,'Alejandrito2', 'ALEJANDRO', 'DEL POZO','EN UN GOZO', '1989/10/20', 'ALEX2@YAHOO.ES','a', 'HUMORISTA', NULL);
    insert into registrado VALUES (NULL,'Samuelito', 'SAMUEL', 'ORTEGA','AZUL', '1995/07/05', 'SAMUEL@YAHOO.ES','a', 'HATER', NULL);
    insert into registrado VALUES (NULL,'Brianciatogg', 'BRIAN', 'VENEZUELA','BARCELONA', '2009/1/1', 'BRIAnN@YAHOO.ES', 'a', 'LINUX', NULL);
    insert into registrado VALUES (NULL,'Josecitoo', 'JOSE', 'GREGORIO','RAYADO', '2002/1/1', 'JOSE@YAHOO.ES', 'a', 'FILOSOFO', NULL);
    insert into registrado VALUES (NULL,'Pepito', 'PEPE', 'GROSO','REFIRTO', '2002/1/05', 'PEPE@YAHOO.ES', 'a', 'ECONOMICAS', NULL);
    insert into registrado VALUES (NULL,'Armandiko', 'ARMANDO', 'DEFIR','SOLIA', '2002/1/05', 'ARMANDO@YAHOO.ES', 'a', 'ECONOMICAS', NULL);
    insert into registrado VALUES (NULL,'Lukita', 'LUKA', 'DONCIC','GREGO', '2002/05/05', 'LUKA@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Rafita', 'RAFAEL', 'NADAL','PAREA', '1994/1/05', 'RAFAEL@YAHOO.ES', 'a', 'TENIS', NULL);
    insert into registrado VALUES (NULL,'Seryito', 'SERGIO', 'GONZALEZ','Davies', '1982/1/05', 'SERYI1@YAHOO.ES', 'a', 'FILOSOFO', NULL);
    insert into registrado VALUES (NULL,'Hugo1', 'Hugo', 'SANCHEZ','Smith', '1982/1/05', 'SERYI2@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Martín12', 'Martín', 'LOPEZ','Jones', '1982/1/05', 'SERYI3@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Lucas32', 'Lucas', 'GARCIA','Williams', '1982/1/05', 'SERYI4@YAHOO.ES', 'a', 'FILOSOFO', NULL);
    insert into registrado VALUES (NULL,'Mateo43', 'Mateo', 'MARTINEZ','Robinson', '1982/1/05', 'SERYI5@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Leo41', 'Leo', 'GONZALEZ','Wood', '1982/1/05', 'SERYI6@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Danielsitoo', 'Daniel', 'GARCIA','Jones', '1982/1/05', 'SERYI7@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Alejandro007', 'Alejandro', 'GONZALEZ','Clark', '1982/1/05', 'SERYI8@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Pablotes', 'Pablo', 'LOPEZ','Smith', '1982/1/05', 'SERYI9@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Manueletes', 'Manuel', 'MARTINEZ','Thompson', '1982/1/05', 'SERYI0@YAHOO.ES', 'a', 'ECONOMICAS', NULL);
    insert into registrado VALUES (NULL,'Álvaro845', 'Álvaro', 'GONZALEZ','Robinson', '1982/1/05', 'SERYI11@YAHOO.ES', 'a', 'FILOSOFO', NULL);
    insert into registrado VALUES (NULL,'Adrián42', 'Adrián', 'GARCIA','Williams', '1982/1/05', 'SERYI22@YAHOO.ES', 'a', 'JAVASCRIPT', NULL);
    insert into registrado VALUES (NULL,'David43', 'David', 'LOPEZ','Jones', '1982/1/05', 'SERYI33@YAHOO.ES', 'a', 'HUMORISTA', NULL);
    insert into registrado VALUES (NULL,'Mariete01', 'Mario', 'GARCIA','Clark', '1982/1/05', 'SERYI44@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Diego_rm', 'Diego', 'GONZALEZ','Smith', '1982/1/05', 'SERYI55@YAHOO.ES', 'a', 'HUMORISTA', NULL);
    insert into registrado VALUES (NULL,'Marcos_Mar', 'Marcos', 'LLULL','Davies', '1982/1/05', 'SERYI66@YAHOO.ES', 'a', 'JAVASCRIPT', NULL);
    insert into registrado VALUES (NULL,'Izancito', 'Izan', 'GOMEZ','Williams', '1982/1/05', 'SERYI77@YAHOO.ES', 'a', 'FILOSOFO', NULL);
    insert into registrado VALUES (NULL,'Javierpes', 'Javier', 'GARCIA','Robinson', '1982/1/05', 'SERYI88@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'MarcoAldany', 'Marco', 'MARTINEZ','Jones', '1982/1/05', 'SERYI99@YAHOO.ES', 'a', 'ECONOMICAS', NULL);
    insert into registrado VALUES (NULL,'Álexitossje', 'Álex', 'GARCIA','Smith', '1982/1/05', 'SERYI00@YAHOO.ES', 'a', 'JAVASCRIPT', NULL);
    insert into registrado VALUES (NULL,'Brunetes', 'Bruno', 'GOMEZ','Williams', '1982/1/05', 'SERYI111@YAHOO.ES', 'a', 'DORMILON', NULL);
    insert into registrado VALUES (NULL,'Oliver_Benji', 'Oliver', 'MARTINEZ','Thompson', '1982/1/05', 'SERYI222@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Miguel_San', 'Miguel', 'SANCHEZ','Jones', '1982/1/05', 'SERYI333@YAHOO.ES', 'a', 'JAVASCRIPT', NULL);
    insert into registrado VALUES (NULL,'Thiaguiñio', 'Thiago', 'LOPEZ','Clark', '1982/1/05', 'SERYI444@YAHOO.ES', 'a', 'BASKET', NULL);
    insert into registrado VALUES (NULL,'Marc_Spenser', 'Marc', 'GOMEZ','Thompson', '1982/1/05', 'SERYI555@YAHOO.ES', 'a', 'ECONOMICAS', NULL);
    insert into registrado VALUES (NULL,'Carlos_Busquet', 'SERGIO', 'GARCIA','Robinson', '1982/1/05', 'SERYI666@YAHOO.ES', 'a', 'HUMORISTA', NULL);
    insert into registrado VALUES (NULL,'Ángelito', 'Ángel', 'GONZALEZ','Williams', '1982/1/05', 'SERYI777@YAHOO.ES', 'a', 'JAVASCRIPT', NULL);
    insert into registrado VALUES (NULL,'JuanitoJuan', 'Juan', 'SANCHEZ','Davies', '1982/1/05', 'SERYI888@YAHOO.ES', 'a', 'HUMORISTA', NULL);
    insert into registrado VALUES (NULL,'Gonzalito09', 'Gonzalo', 'GARCIA','Smith', '1982/1/05', 'SERYI999@YAHOO.ES', 'a', 'ECONOMICAS', NULL);


    insert into club VALUES (NULL, 'FORMULA UEM', 'El equipo está formado por estudiantes de ingenieria, diseño, marketing, negocios... interesados en el mundo del motorsport y que están buscando un reto. Trabajamos en el diseño y fabricación de un monoplaza para competir contra otras universidades tanto a nivel nacional como internacional.', 'clubF1UEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CLUB INFORMÁTICA', 'Somos un club multidisciplinar basado en proyectos de nuevas tecnologías como loT Cloud, drones, etc., además de los propios de la informática y la programación.', 'clubPROGRAMACIONUEM@GMAIL.COM',now(), NULL, NULL,'Canarias');
    insert into club VALUES (NULL, 'IRL CLUB', 'En el Club de Relaciones Internacionales, somos un grupo diverso de estudiantes de diferentes partes del mundo, que nos hemos reunido por nuestro gran interés en las Relaciones Internacionales. Realizamos entrevistas en directo en Instagram, debates...', 'clubDEBATESUEM@GMAIL.COM',now(), NULL, NULL,'Valencia');
    insert into club VALUES (NULL, 'GAME STUDIO 2.0', 'Unimos arte, diseño y programación para la creación de videojuegos. Organizamos cursos de programación con Gamemaker, game jams, torneos de e-sports, etc.', 'clubVIDEOJUEGOSUEM@GMAIL.COM',now(), NULL, NULL,'Alcobendas');
    insert into club VALUES (NULL, 'BDE KINESPAÑA', 'Queremos ser parte de la integración de los nuevos y futuros estudiantes de Fisioterapia, a través de diversas actividades recreativas y eventos deportivos. Nuestro objetivo es ayudar a los estudiantes en Su paso por la universidad y que se sientan el orgullo de ser parte de la Universidad Europea de Madrid', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CLUB ROBOTICS', 'Creamos desde cero sistemas robóticos así como el manejo de sistemas ya desarrollados. Participamos en concursos de robótica como el ASTIC hallenge, proyectos independientes como el Robot Araña, etc.', 'clubroboticsuem@gmail.com',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CRIPTO CLUB', 'Queremos explorar el potencial que tiene la tecnologia del blockchain y la descentralización para cambiar la economia tal y como la conocemos. Estudia lo aspectos fundamentales e importantes relacionados con la economía descentralizada para mejorar la toma de decisiones.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'UEM E-SPORTS', 'Nos apasionan los deportes electrónicos y queremos ofrecer a la comunidad de la Universidad Europea de Madrid eventos y competencias de e-sports. Nos definimos como unos "frikis" que se reúnen para jugar a videojuegos en comunidad.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CLUB AIR DIVISION', 'Diseñamos y fabricamos drones,. y actualmente estamos preparando el lanzamiento del satélite a través del proyecto PicoSat mediante colaboradores. Visitamos centros del sector aeronáutico y aeroespacial.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'RUNNING CLUB', 'Si te apasiona correr, quieres ponerte en forma y conocer gente, ieste es tu club! Podrás disfrutar de entrenamientos semanales guiados por un instructor de running titulado. Entrena con nosotros, consigue dorsales en carreras seleccionadas y tu equipamiento deportivo de la Universidad Europea de Valencia.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'WORKOUT VALENCIA', 'Para los que no pueden estar quietos. Entrenamientos semanales para todas las edades y todos los niveles, lo importante es que tengas ganas de estar en forma y de pasarlo bien al aire libre, y sin necesidad de equipamiento.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CHESS CLUB', 'No importa si llevas mucho tiempo jugando al ajedrez o si quieres aprender, en el Chess Club queremos unir a todos los estudiantes entornoa este juego. Forma parte de nuestro club y te la oportunidad de compartir con estudiantes de todas las titulaciones mientras desarrollas tus habilidades con el ajedrez.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'ASOCIACIÓN DE ODONTOLOGÍA', 'Por y para los estudiantes. Queremos proporcionar conocimientos, experiencias y ser un punto de encuentro para los estudiantes de Odontología de la Universidad Europea de Madrid.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'AEMUEM', 'Unete a la Asociación de Estudiantes de Medicina UEM! Si estudias Medicina y quieres relacionarte con otros estudiantes de tu Facultad fuera de las clases, con proyectosyactividades que te interesen. Además, la Asociación representa tu voz y tu opinión.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'UEPSA', 'En la Universidad Europea Psychology Student Association, nuestro objetivo es promover la salud mental y combatir el estigma de las enfermedades mentales. Para fomentar la relación entre los miembros, organizamos debates y otras actividades sociales como cinefórums y picnics en el parque.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'DENTALIFE', 'DentaLife es un club dedicado a la vida estudiantil de los futuros dentistas de la UEM. Nuestro objetivo es promover la cohesión de los estudiantes mediante la creación de eventos festivos, culturales y deportivos.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'PHYSX', 'Somos un club que se enfrenta a retos enfocados al área de la física e intentar darles sentido a los datos obtenidos, no tenemos límites, actualmente estamos reconstruyendo una caseta meteorológica, también estamos con la construcción de un contador Geiger.', 'PHYSX@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CLUB DE CIENCIA', 'Preparamos actividades, talleres e iniciativas relacionadas con el mundo de la ciencia. Es un lugar donde promovemos las aplicaciones de las Ciencias y desarrollamos nuevas habilidades de una forma divertida y amena.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CLUB MUN ', 'Queremos crear un espacio universitario donde los estudiantes del mundo puedan poner en práctica las teorías aprendidas en clases y las teorías metodológicas de las relaciones internacionales, a través de Modelos de Naciones Unidas y distintos organismos globales.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'PRIDE UE', 'Si estás buscando un espacio dónde aprender, compartir y vivir experiencias dentro de la comunidad LGTBIQ+, este es tu club. Nuestro objetivo principal es crear un espacio abierto para todas aquellas personas que sean del colectivo, lo apoyen o simplemente quieran conocerlo más.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CLUB DE ROL', 'Un espacio donde puedes reforzar tu creatividad y tus capacidades de improvisación a la vez que aprendes competencias relacionadas con el ambiente narrativo y de diseño encontrado en diversos estudios de videojuegos. Organizamos diversos talleres y partidas de rol.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CLUB DE TEATRO', 'Te apasiona la actuación? ¿Quieres descubriro desarrollar tus talentos? Sé parte del Club de Teatro y vive la experiencia de representar una obra. Cada semana aprenderás lo que ocurre en el proceso de montaje de una obra de teatro y la experiencia desde el punto de vista de los actores.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'CLUB DE FOTOGRAFÍA', ' Si te interesa la fotografía, la creación de videos, la escritura de guiones o incluso el manejo de drones con fines audiovisuales, este es tu club. Somos un grupo de estudiantes con interés en aprender y poner en práctica conocimientos sobre el mundo audiovisual.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'UECC', '¡Hablemos de cine! El objetivo del Universidad Europea Cinema Club es llegar a conocer más sobre el séptimo arte y compartir ideas sobre películas desde diversos enfoques como la filosofia, la cinematografía, la psicología, etc. Es un entorno en el que debatimos e intercambiamos nuestras perspectivas sobre el tema.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');
    insert into club VALUES (NULL, 'PSYCLUB', 'Somos un grupo de alumnos que tiene como objetivo la divulgación de información cientifica mediante charlas y actividades en las que los alumnos y alumni de la UE pueden participar. Buscando asi romperlos estigmas, mitos y desinformación con respecto a la psicologia, ¿Te interesa? Siguenos en instogrom y entérate de las actividades mensudles.', 'clubFISIOTERAPIAUEM@GMAIL.COM',now(), NULL, NULL,'Villaviciosa');


    insert into proyecto VALUES (NULL, 'DESARROLLO DE NEUMATICO F1', 'PROYECTO PARA DESARROLLAR NEUMATICOS PARA EL F1', 'proyecto1@GMAIL.COM', now(), 1, 1, NULL);
    insert into proyecto VALUES (NULL, 'F1', 'PROYECTO PARA DESARROLLAR NEUMATICOS PARA EL F1', 'proyecto11@GMAIL.COM', now(), 0, 1, NULL);
    insert into proyecto VALUES (NULL, 'PROGRAMACIÓN DE DRONES', 'PROYECTO PARA DESARROLLAR DRONES AUTOMATIZADOS', 'proyecto21@GMAIL.COM', now(), 1, 2, NULL);
    insert into proyecto VALUES (NULL, 'DRONES', 'PROYECTO PARA DESARROLLAR DRONES AUTOMATIZADOS', 'proyecto2@GMAIL.COM', now(), 0, 2, NULL);
    insert into proyecto VALUES (NULL, 'DEBATE SOBRE LA POLÍTICA', 'PROYECTO PARA DESARROLLAR HABILIDADES DE DEBATE', 'proyecto3@GMAIL.COM', now(), 0, 3, NULL);
    insert into proyecto VALUES (NULL, 'LA POLÍTICA', 'PROYECTO PARA DESARROLLAR HABILIDADES DE DEBATE', 'proyecto31@GMAIL.COM', now(), 0, 3, NULL);
    insert into proyecto VALUES (NULL, 'VIDEOJUEGO INDIE ', 'PROYECTO PARA DESARROLLAR UN NUEVO VIDEOJUEGO AL ESTILO INDIE', 'proyecto4@GMAIL.COM', now(), 1, 4, NULL);
    insert into proyecto VALUES (NULL, 'VR 3D', 'PROYECTO PARA DESARROLLAR UN VIDEOJUEGO EN 3D', 'proyecto14@GMAIL.COM', now(), 0, 4, NULL);
    insert into proyecto VALUES (NULL, '¿PREPARADO?', 'PROYECTO PARA TRABAJAR EN UN JUEGO QUE DEJARA A TODOS SORPENDIDO', 'proyecto14@GMAIL.COM', now(), 1, 4, NULL);

    insert into proyecto VALUES (NULL, 'APRENDE A DAR MASAJES', 'PROYECTO PARA APRENDER A DAR MASAJES', 'proyecto5@GMAIL.COM', now(), 1, 5, NULL);
    insert into proyecto VALUES (NULL, 'DAR MASAJES', 'PROYECTO PARA APRENDER A DAR MASAJES', 'proyecto51@GMAIL.COM', now(), 0, 5, NULL);
    insert into proyecto VALUES (NULL, 'COMO SE RPP', 'PROYECTO PARA APRENDER COMO SER RELACIONES PUBLICAS EN EL AMBITO QUE TU QUIERAS', 'proy1ecto6@GMAIL.COM',now(), 1, 6, NULL);
    insert into proyecto VALUES (NULL, 'RPP', 'PROYECTO PARA APRENDER COMO SER RELACIONES PUBLICAS EN EL AMBITO QUE TU QUIERAS', 'proyecto6@GMAIL.COM',now(), 0, 6, NULL);
    insert into proyecto VALUES (NULL, 'DIRIGIR UNA PELICULA', 'PROYECTO PARA APRENDER COMO SE SIENTE UN DIRECTOR AL LLEVAR UNA PELICULA ', 'proyecto7@GMAIL.COM',now(), 1, 7, NULL);
    insert into proyecto VALUES (NULL, 'UNA PELICULA', 'PROYECTO PARA APRENDER COMO SE SIENTE UN DIRECTOR AL LLEVAR UNA PELICULA ', 'proyecto71@GMAIL.COM',now(), 0, 7, NULL);
    insert into proyecto VALUES (NULL, 'ALFIN CABALLO REY', 'PROYECTO PARA PODER MEJORAR TUS HABILIDADES EN EL AJEDREZ Y LLEGAR A SER EL MEJOR',  'proyecto8@GMAIL.COM',now(),1, 8, NULL);
    insert into proyecto VALUES (NULL, 'REY', 'PROYECTO PARA PODER MEJORAR TUS HABILIDADES EN EL AJEDREZ Y LLEGAR A SER EL MEJOR','proyecto81@GMAIL.COM', now(), 0, 8, NULL);
    insert into proyecto VALUES (NULL, 'TU PSICOLOGO', 'PROYECTO PARA CONOCERTE A TI MISMO Y SER CAPAZ DE RESOLVER TUS PROBLEMAS', 'proyecto19@GMAIL.COM',now(),  1, 9, NULL);
    insert into proyecto VALUES (NULL, 'TU', 'PROYECTO PARA CONOCERTE A TI MISMO Y SER CAPAZ DE RESOLVER TUS PROBLEMAS', 'proyecto9@GMAIL.COM',now(),  0, 9, NULL);
    insert into proyecto VALUES (NULL, 'HIMNOS MADRIDISTA', 'PROYECTO PARA FORMULAR NUEVOS HIMNOS PARA EL REAL MADRID','proyecto10@GMAIL.COM', now(), 1, 10, NULL);
    insert into proyecto VALUES (NULL, 'HIMNOS', 'PROYECTO PARA FORMULAR NUEVOS HIMNOS PARA EL REAL MADRID',  'proyecto101@GMAIL.COM',now(),0, 10, NULL);
    insert into proyecto VALUES (NULL, 'DRAGONES Y MAZMORRAS', 'PROYECTO PARA PODER CREAR LA MEJOR PARTIDA POSIBLE EN LA UNIVERSIDAD','proyec2to11@GMAIL.COM', now(), 1, 11, NULL);
    insert into proyecto VALUES (NULL, 'DRAGONES', 'PROYECTO PARA PODER CREAR LA MEJOR PARTIDA POSIBLE EN LA UNIVERSIDAD', 'proye2cto111@GMAIL.COM',now(), 0, 11, NULL);
    insert into proyecto VALUES (NULL, 'NFTS', 'PROYECTO PARA PODER INVERTIR TU TIEMPO EN NUEVAS INVERSIONES QUE HARAN GANAR DINERO','proyecto121@GMAIL.COM', now(), 1, 12, NULL);
    insert into proyecto VALUES (NULL, 'WILLYY', 'PROYECTO PARA PODER INVERTIR TU TIEMPO EN NUEVAS INVERSIONES QUE HARAN GANAR DINERO', 'proyect1o12@GMAIL.COM',now(), 0, 12, NULL);
    insert into proyecto VALUES (NULL, 'LA CARRERA', 'PROYECTO PARA PODER ORGANIZAR LA CARRERA MAS GRANDE EN LOS ALREDEDORES DE NUESTRA ZONA', 'proyecto1311@GMAIL.COM', now(),1, 13, NULL);
    insert into proyecto VALUES (NULL, 'CARRERA', 'PROYECTO PARA PODER ORGANIZAR LA CARRERA MAS GRANDE EN LOS ALREDEDORES DE NUESTRA ZONA', 'proyecto1333@GMAIL.COM',now(), 0, 13, NULL);
    insert into proyecto VALUES (NULL, 'DEMOSTRANDO0', 'PROYECTO PARA PODER DEMOSTRAR DISTINTAS TEORIAS QUE NOS HEMOS PLANTEADO EN NUESTRA VIDA','proyecto1424@GMAIL.COM', now(), 0, 14, NULL);
    insert into proyecto VALUES (NULL, 'SALTADOR', 'PROYECTO PARA PODER FABRICAR UN SALTADOR PORTATIL DE FACIL USO','proyecto15124@GMAIL.COM', now(), 1, 15, NULL);
    insert into proyecto VALUES (NULL, 'SALTADORESS', 'PROYECTO PARA PODER FABRICAR UN SALTADOR PORTATIL DE FACIL USO',  'proyecto15241@GMAIL.COM',now(),0, 15, NULL);
    insert into proyecto VALUES (NULL, 'HARDWARE', 'PROYECTO PARA APRENDER A DESMONATAR Y MONTAR Y LAS PARATES DE UN ORDENADOR', 'proyecto16124@GMAIL.COM',now(), 1, 16, NULL);
    insert into proyecto VALUES (NULL, '!SUUU¡', 'PROYECTO PARA APRENDER A DESMONATAR Y MONTAR Y LAS PARATES DE UN ORDENADOR',  'proyecto16124@GMAIL.COM',now(),0, 16, NULL);
    insert into proyecto VALUES (NULL, 'MANITAS', 'PROYECTO PARA APRENDER SOBRE LA MECANICA DE LOS COCHES Y SU FUNCIONAMIENTO', 'proyecto17124@GMAIL.COM',now(), 1, 16, NULL);
    insert into proyecto VALUES (NULL, 'MANI MANITAS', 'PROYECTO PARA APRENDER SOBRE LA MECANICA DE LOS COCHES Y SU FUNCIONAMIENTO', 'proyecto17145@GMAIL.COM',now(), 0, 13, NULL);

    insert into proyecto VALUES (NULL, 'DEMOSTRANDO', 'PROYECTO PARA PODER DEMOSTRAR DISTINTAS TEORIAS QUE NOS HEMOS PLANTEADO EN NUESTRA VIDA', 'physx@gmail.com',now(), 0, 17, NULL);
    insert into proyecto VALUES (NULL, 'EL PROYECTAZO', 'ULTIMO PROYETCO DEL AÑO EN EL QUE TIRAREMOS LA UNI POR LA BORDA DEMOSTRANDO, CREANDO Y DEBATIRNDO SOBRE NUEVAS TEORIAS', 'physx@gmail.com',now(), 0, 17, NULL);



    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 1, 10);
    insert into noticia_club VALUES (NULL, now(),'Alonsoo', 'Este martes reuinion con Fernando Alonso', 1, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 2, 11);
    insert into noticia_club VALUES (NULL, now(),'Arduinos coseguido', 'El proximo martes podremos realizar el curso de robotica gracias a los arduinos conseguidos', 2, 8);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE DEBATE! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 3, 9);
    insert into noticia_club VALUES (NULL, now(),'Reunion a lo grande','Este jueves realizaremos una reunion en la que participara gente de todos los paises, no te lo pierdas', 3, 16);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE VIDEOJUEGOS! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 4, 15);
    insert into noticia_club VALUES (NULL, now(),'Beta Testers', 'No te pierdas el encuentro del martes que viene probando la version beta de nuestro nuevo juego', 4, 8);
    insert into noticia_club VALUES (NULL, now(),'Gamecon', 'Este jueves quedad en la gamecon , no os lo perdais y no falteis que sera la bomba ', 4, 10);
    insert into noticia_club VALUES (NULL, now(),'Retro', 'No faltes al sabado retro de este finde semana, habra inumerables juegos retro para probar', 4, 11);
    insert into noticia_club VALUES (NULL, now(),'Despedida', 'Nos despedimos este domingo con el final de curso con una reunioncilla no faltes', 4, 12);

    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 5, 14);
    insert into noticia_club VALUES (NULL, now(),'¡Masajes Gratis!', 'El finde que vienes todos los participantes del club tendran que dar masajes gratis a todos los nuevos integrantes', 5, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 6, 15);
    insert into noticia_club VALUES (NULL, now(),'Empieza el proyecto', 'No te pierdas mañna el comienzo del robo-proyecto que empezaremos hacer lluvia de ideas', 6, 11);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 7, 13);
    insert into noticia_club VALUES (NULL, now(),'Invertimos a lo grande', 'Cuidado no te pierdas la gran inversion conjunta que haremos el proximo viernes, podria salir muy bien.', 7, 11);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 8, 7);
    insert into noticia_club VALUES (NULL, now(),'Torneito', 'Quiers participar en la creacion de un torneo gigante?,no te pierdas la quedada de este miercoles', 8, 7);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 9, 8);
    insert into noticia_club VALUES (NULL, now(),'!ZoooOOOMMmm¡', 'No te pierdas la carrera de prueba de dornes fabricado en nuestro club', 9, 8);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 10, 9);
    insert into noticia_club VALUES (NULL, now(),'3,2,1,Yaa', 'Carerra mañana, no te pierdas una buena carrera en la que participara muchisima gente', 10, 9);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 11, 10);
    insert into noticia_club VALUES (NULL, now(), 'Entrenamiento', 'No te pierdas el proximo entrenamiento conjunto liderado por Javir, nuestro gran coordinador', 11, 10);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 12, 11);
    insert into noticia_club VALUES (NULL, now(),'Jaque Mate', 'Podras ganar el proximo torneo solo si asistes asi que no te lo pierdas, grndes premios te esperan', 12, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 13, 11);
    insert into noticia_club VALUES (NULL, now(),'Ratocito Perez', 'Preparado para la busqueda del diente perdido? No te pierdas el siguiente juego que realizaremos el proximo martes', 13, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 14, 11);
    insert into noticia_club VALUES (NULL, now(),'¿Vacunarse o no?', 'Hoy debatiremos sobre si vale la pena vacunarse a estas alturas del covid no te lo pierdas', 14, 14);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 15, 13);
    insert into noticia_club VALUES (NULL, now(),'¿Alguien dijo Terapia?', 'El miercoles que viene practicaremos sesiones de terapia para ver que tal andais de salud mental', 15, 16);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 16, 7);
    insert into noticia_club VALUES (NULL, now(),'Dentistas aqui', 'Este martes practicaremos en bocas de prueba la extraccion de muelas animate y pasate un ratillo', 16, 9);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 17, 11);
    insert into noticia_club VALUES (NULL, now(),'Teorias', 'El lunes que viene intentaremos desmontar alguna teoria no te pierdas esta fascinante aventura', 17, 14);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 18, 11);
    insert into noticia_club VALUES (NULL, now(),'Experimentos', 'No te pierdas el miercoles loco, donde haremos nuevos experimentos ', 18, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 19, 8);
    insert into noticia_club VALUES (NULL, now(),'Unimos manos', 'Este martes debatiremos como esta actuando manos unidas', 19, 9);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 20, 11);
    insert into noticia_club VALUES (NULL, now(),'Abrete', 'Cuentanos tus experencia y te escuchamos, este martes haremos una reunion para abrirnos y hablar sobre temas', 20, 13);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 21, 11);
    insert into noticia_club VALUES (NULL, now(),'Disfraces', 'En el torneo de este sabado habra que venir bien vestido, trae un disfraz o el dragon te comera', 21, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 22, 14);
    insert into noticia_club VALUES (NULL, now(),'Sonrisas y lagrimas', 'Mañana replicaremos la obra de teatro preparate el papel', 22, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 23, 11);
    insert into noticia_club VALUES (NULL, now(),'Sesioneo que te veo', 'Este domingo haremos una escursion por madrid de sesioneo', 23, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 24, 15);
    insert into noticia_club VALUES (NULL, now(),'¡Debateee!', 'Esta ade debate sobre la meor pelicula de este mes', 24, 12);
    insert into noticia_club VALUES (NULL, now(),'Primera noticia club', '¡BIENVENIDOS AL club DE FORMULA 1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 25, 13);
    insert into noticia_club VALUES (NULL, now(),'Clases', 'Esta semana daremos clases a gente de la uni estate atento para no perderte el dia', 25, 12);


    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE DESARROLLO DE NEUMATICOS F1! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 1, 11);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE PROGRAMACIÓN DE DRONES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 1, 12);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE DEBATE SOBRE LA POLÍTICA ESPAÑOLA! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 1, 13);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE VIDEOJUEGO INDIE 3D! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 3, 13);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS',4, 14);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 5, 15);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 6, 6);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 7, 7);
    insert into noticia_proyecto VALUES (NULL, now(),'Ouououo', '¿NO TE HASA ENTERADO TODAVIA?, ESTA A PUNTO DE DESARROLARSE EL HUEGO DEL AÑO, NO TE PIERDAS LA QUEDADA EST SABADO', 7, 7);
    insert into noticia_proyecto VALUES (NULL, now(),'Despedida', 'REUNION DE ANTIGUOS INTEGRANTES DEL PROYECTO Y NUEVOS PARTICIPANTES UNA CHARLA QUE NO TE PUEDES PERDER MAÑANA', 7, 7);

    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 8, 8);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 9, 9);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 10, 10);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 11, 11);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 12, 12);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 13, 13);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 14, 14);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 15, 15);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 16, 16);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 17, 17);
    insert into noticia_proyecto VALUES (NULL, now(),'Primera noticia proyecto', '¡BIENVENIDOS AL proyecto DE APRENDE A DAR MASAJES! ESTA ES NUESTRA PRIMERA noticia PARA PRESENTARNOS A TODOS', 18, 18);


    insert into pert_proyecto VALUES (1, 1, now());
    insert into pert_proyecto VALUES (1, 2, now());
    insert into pert_proyecto VALUES (1, 3, now());
    insert into pert_proyecto VALUES (1, 4, now());
    insert into pert_proyecto VALUES (1, 5, now());
    insert into pert_proyecto VALUES (1, 6, now());
    insert into pert_proyecto VALUES (1, 7, now());
    insert into pert_proyecto VALUES (1, 8, now());
    insert into pert_proyecto VALUES (1, 9, NULL);
    insert into pert_proyecto VALUES (1, 10, NULL);
    insert into pert_proyecto VALUES (1, 11, NULL);
    insert into pert_proyecto VALUES (10, 1, now());
    insert into pert_proyecto VALUES (11, 1, now());
    insert into pert_proyecto VALUES (12, 1, now());
    insert into pert_proyecto VALUES (13, 1, now());
    insert into pert_proyecto VALUES (14, 1, now());
    insert into pert_proyecto VALUES (15, 1, NULL);
    insert into pert_proyecto VALUES (16, 1, now());
    insert into pert_proyecto VALUES (17, 1, now());
    insert into pert_proyecto VALUES (18, 1, now());
    insert into pert_proyecto VALUES (19, 1, NULL);
    insert into pert_proyecto VALUES (20, 1, now());
    insert into pert_proyecto VALUES (21, 1, now());
    insert into pert_proyecto VALUES (22, 1, NULL);
    insert into pert_proyecto VALUES (23, 1, now());
    insert into pert_proyecto VALUES (10, 2, now());
    insert into pert_proyecto VALUES (11, 2, now());
    insert into pert_proyecto VALUES (12, 2, NULL);
    insert into pert_proyecto VALUES (13, 2, now());
    insert into pert_proyecto VALUES (14, 2, now());
    insert into pert_proyecto VALUES (15, 2, NULL);
    insert into pert_proyecto VALUES (16, 2, now());
    insert into pert_proyecto VALUES (17, 2, NULL);
    insert into pert_proyecto VALUES (18, 2, now());
    insert into pert_proyecto VALUES (19, 2, NULL);
    insert into pert_proyecto VALUES (20, 2, now());
    insert into pert_proyecto VALUES (21, 2, now());
    insert into pert_proyecto VALUES (22, 2, NULL);
    insert into pert_proyecto VALUES (23, 2, now());
    insert into pert_proyecto VALUES (7, 3, now());
    insert into pert_proyecto VALUES (8, 3, now());
    insert into pert_proyecto VALUES (9, 3, NULL);
    insert into pert_proyecto VALUES (10, 3, now());
    insert into pert_proyecto VALUES (11, 3, now());
    insert into pert_proyecto VALUES (12, 3, NULL);
    insert into pert_proyecto VALUES (13, 3, now());
    insert into pert_proyecto VALUES (14, 3, NULL);
    insert into pert_proyecto VALUES (15, 3, now());
    insert into pert_proyecto VALUES (16, 3, NULL);
    insert into pert_proyecto VALUES (17, 3, now());
    insert into pert_proyecto VALUES (18, 3, now());
    insert into pert_proyecto VALUES (19, 3, NULL);
    insert into pert_proyecto VALUES (20, 3, now());
    insert into pert_proyecto VALUES (2, 2, now());
    insert into pert_proyecto VALUES (3, 3, now());
    insert into pert_proyecto VALUES (4, 4, now());
    insert into pert_proyecto VALUES (34, 1, now());
    insert into pert_proyecto VALUES (34, 2, now());
    insert into pert_proyecto VALUES (34, 3, now());
    insert into pert_proyecto VALUES (34, 4, now());
    insert into pert_proyecto VALUES (34, 5, now());
    insert into pert_proyecto VALUES (34, 6, now());
    insert into pert_proyecto VALUES (35, 7, now());
    insert into pert_proyecto VALUES (35, 8, now());
    insert into pert_proyecto VALUES (35, 9, now());
    insert into pert_proyecto VALUES (35, 10, now());
    insert into pert_proyecto VALUES (35, 11, now());
    insert into pert_proyecto VALUES (36,12 , now());
    insert into pert_proyecto VALUES (36, 13, now());
    insert into pert_proyecto VALUES (36, 14, now());
    insert into pert_proyecto VALUES (36,15 , now());
    insert into pert_proyecto VALUES (36,16 , now());
    insert into pert_proyecto VALUES (36, 17, now());





    insert into rep_proyecto VALUES (1, 1);
    insert into rep_proyecto VALUES (1, 2);
    insert into rep_proyecto VALUES (1, 3);
    insert into rep_proyecto VALUES (10, 1);
    insert into rep_proyecto VALUES (11, 1);
    insert into rep_proyecto VALUES (12, 1);
    insert into rep_proyecto VALUES (2, 2);
    insert into rep_proyecto VALUES (3, 3);
    insert into rep_proyecto VALUES (4, 4);


    insert into pert_club VALUES (1, 1, now());
    insert into pert_club VALUES (1, 2, now());
    insert into pert_club VALUES (1, 3, now());
    insert into pert_club VALUES (1, 4, now());
    insert into pert_club VALUES (1, 5, now());
    insert into pert_club VALUES (1, 6, now());
    insert into pert_club VALUES (1, 7, now());
    insert into pert_club VALUES (1, 8, now());
    insert into pert_club VALUES (1, 9, NULL);
    insert into pert_club VALUES (1, 10, NULL);
    insert into pert_club VALUES (1, 11, NULL);
    insert into pert_club VALUES (1, 12, NULL);
    insert into pert_club VALUES (1, 13, NULL);
    insert into pert_club VALUES (1, 14, NULL);
    insert into pert_club VALUES (1, 15, NULL);
    insert into pert_club VALUES (1, 16, NULL);
    insert into pert_club VALUES (1, 17, NULL);
    insert into pert_club VALUES (1, 18, NULL);
    insert into pert_club VALUES (1, 19, NULL);
    insert into pert_club VALUES (1, 20, NULL);
    insert into pert_club VALUES (1, 21, NULL);
    insert into pert_club VALUES (1, 22, NULL);
    insert into pert_club VALUES (1, 23, NULL);
    insert into pert_club VALUES (10, 1, now());
    insert into pert_club VALUES (11, 1, now());
    insert into pert_club VALUES (12, 1, now());
    insert into pert_club VALUES (13, 1, now());
    insert into pert_club VALUES (14, 1, now());
    insert into pert_club VALUES (15, 1, NULL);
    insert into pert_club VALUES (16, 1, now());
    insert into pert_club VALUES (17, 1, now());
    insert into pert_club VALUES (18, 1, now());
    insert into pert_club VALUES (19, 1, NULL);
    insert into pert_club VALUES (20, 1, now());
    insert into pert_club VALUES (21, 1, now());
    insert into pert_club VALUES (22, 1, NULL);
    insert into pert_club VALUES (23, 1, now());

    insert into pert_club VALUES (24, 1, now());
    insert into pert_club VALUES (25, 1, now());
    insert into pert_club VALUES (26, 1, now());
    insert into pert_club VALUES (27, 1, now());
    insert into pert_club VALUES (28, 1, now());
    insert into pert_club VALUES (29, 1, now());
    insert into pert_club VALUES (30, 1, now());
    insert into pert_club VALUES (31, 1, now());
    insert into pert_club VALUES (32, 1, now());
    insert into pert_club VALUES (33, 1, now());
    insert into pert_club VALUES (34, 1, now());
    insert into pert_club VALUES (35, 1, now());
    insert into pert_club VALUES (36, 1, now());
    insert into pert_club VALUES (37, 1, now());
    insert into pert_club VALUES (38, 1, now());
    insert into pert_club VALUES (39, 1, now());
    insert into pert_club VALUES (40, 1, now());
    insert into pert_club VALUES (10, 2, now());
    insert into pert_club VALUES (11, 2, now());
    insert into pert_club VALUES (12, 2, NULL);
    insert into pert_club VALUES (13, 2, now());
    insert into pert_club VALUES (14, 2, now());
    insert into pert_club VALUES (15, 2, NULL);
    insert into pert_club VALUES (16, 2, now());
    insert into pert_club VALUES (17, 2, NULL);
    insert into pert_club VALUES (18, 2, now());
    insert into pert_club VALUES (19, 2, NULL);
    insert into pert_club VALUES (20, 2, now());
    insert into pert_club VALUES (21, 2, now());
    insert into pert_club VALUES (22, 2, NULL);
    insert into pert_club VALUES (23, 2, now());
    insert into pert_club VALUES (7, 3, now());
    insert into pert_club VALUES (8, 3, now());
    insert into pert_club VALUES (9, 3, NULL);
    insert into pert_club VALUES (10, 3, now());
    insert into pert_club VALUES (11, 3, now());
    insert into pert_club VALUES (12, 3, NULL);
    insert into pert_club VALUES (13, 3, now());
    insert into pert_club VALUES (14, 3, NULL);
    insert into pert_club VALUES (15, 3, now());
    insert into pert_club VALUES (16, 3, NULL);
    insert into pert_club VALUES (17, 3, now());
    insert into pert_club VALUES (18, 3, now());
    insert into pert_club VALUES (19, 3, NULL);
    insert into pert_club VALUES (20, 3, now());


    insert into rep_club VALUES (1, 1);
    insert into rep_club VALUES (1, 2);
    insert into rep_club VALUES (1, 3);
    insert into rep_club VALUES (1, 7);
    insert into rep_club VALUES (12, 1);
    insert into rep_club VALUES (13, 1);
    insert into rep_club VALUES (14, 1);
    insert into rep_club VALUES (2, 2);
    insert into rep_club VALUES (2, 5);

  
